---
title: HTML headings
format:
  html:
    toc: true
    number-sections: true
    embed-resources: true
---

# HTML headings

- HTML headings are defined width the `<h1>` to `<h6>` tags
- `<h1>` defines the most important heading.
- `<h6>` defines the least important heading.

# Headings are important

Search engines use the headings to index the structure and content of your web pages.

Users often skim a page by its headings. It is important to use headings to show the document structure.

`<h1>` headings should be used for main headings, followed by `<h2>` headings, then the less important `<h3>`, and so on.

For example:

- `<h1>`: page title
- `<h2>`: section titles
- `<h3>`: sub-sections

When using `<code>` in pure html remember the **HTML Entities** (or named character references). They always start with an ampersand (`&`) and end with a semicolon `(;)`:

- `lt`: **l**ess **t**han (`<`: `&lt;`)
- `gt`: **g**reater **t**han (`>`: `&gt;`)

# Bigger headings 

Each HTML heading has a default size. However, you can specify the size for any heading with the `style` attribute, using CSS `font-size` property.

# HTML horizontal rules

The `<hr>` tag defines a thematic break in an HTML page, and is most often displayed as a horizontal rule.

The `<hr>` element is used to separate content (or define a change) in an HTML page.

::: {#nte-hr .callout-note} 
The tag `<hr>` stands for **h**orizontal **r**ule.
:::

The `<hr>` tag is an empty tag, which means that it has no end tag.

# HTML line breaks

The HTML `<br>` element defines a line break.

Use `<br>` if you want a line break (a new line) without starting a new paragraph.

::: {#nte-br .callout-note}
The tag `<br>` stands for **br**eak.
:::

The `<br>` tag is an empty tag, which means that it has no end tag.

# The poem problem